### ISSUE TITLE
Issues making a search function accessing mongoDB

### ISSUE THREAD

**Issue by davenhauser** [davenhauser/musee_app#1]
What user story am I working on?
- As a user I want to use the search bar to search by artist name.

What error am I getting?
- When I use the search bar, it returns an object  with the name of the artist but I don't get it to return the records of this artist. 

<img width="386" alt="screen shot 2016-04-06 at 1 38 43 pm" src="https://cloud.githubusercontent.com/assets/16462453/14333810/69cd5bac-fc05-11e5-828b-a1c9312abdd8.png">

-What have I attempted?
I had a search bar working for my API but am now using a local db stored in mongodb.
I tried to rewrite what I already had without success. I could not find any examples from our class to solve this problem. I read through the mongodb documentation and searched on Stackoverflow (and other sites) but could not find any accurate information). Time spent trying to solve this problem is aprox. 4 hours.

**Comment by jim-clark** [comment]
Fixed
